### ISSUE TITLE
hazen snr – failure on Canon data

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/hazen#157]
From David Price:

> Unfortunately when I attempt to run the images I collected through Hazen I get an error.  It worked fine on the previous Canon system if I recall.- change to header related to manufacturer name.
> Could this be raised as an urgent issue?
>  
> Thanks
>  
> David
>  
> ```bash
> (hazen-venv) Davids-MacBook-Pro:hazen davidprice$ hazen snr QD_Hd_SNR_tra
> Traceback (most recent call last):
>   File "/Users/davidprice/hazen-venv/bin/hazen", line 11, in <module>
>     load_entry_point('hazen==0.3.0', 'console_scripts', 'hazen')()
>   File "/Users/davidprice/hazen-venv/lib/python3.6/site-packages/hazen-0.3.0-py3.6.egg/hazenlib/__init__.py", line 320, in main
>     return pp.pprint(task.main(dicom_objects, report_path=report))
>   File "/Users/davidprice/hazen-venv/lib/python3.6/site-packages/hazen-0.3.0-py3.6.egg/hazenlib/snr.py", line 319, in main
>     snr, normalised_snr = snr_by_subtraction(data[0], data[1], measured_slice_width, report_path)
>   File "/Users/davidprice/hazen-venv/lib/python3.6/site-packages/hazen-0.3.0-py3.6.egg/hazenlib/snr.py", line 280, in snr_by_subtraction
>     normalised_snr = snr * get_normalised_snr_factor(dcm1, measured_slice_width)
>   File "/Users/davidprice/hazen-venv/lib/python3.6/site-packages/hazen-0.3.0-py3.6.egg/hazenlib/snr.py", line 65, in get_normalised_snr_factor
>     dx, dy = hazenlib.get_pixel_size(dcm)
>   File "/Users/davidprice/hazen-venv/lib/python3.6/site-packages/hazen-0.3.0-py3.6.egg/hazenlib/__init__.py", line 204, in get_pixel_size
>     manufacturer = get_manufacturer(dcm)
>   File "/Users/davidprice/hazen-venv/lib/python3.6/site-packages/hazen-0.3.0-py3.6.egg/hazenlib/__init__.py", line 141, in get_manufacturer
>     raise Exception(f'{manufacturer} not recognised manufacturer')
> Exception: canon_mec not recognised manufacturer
> ```

Dicom file = `QD_Hd_SNR1.dcm` – I can supply if necessary.

**Comment by tomaroberts** [comment]
Pretty sure I've fixed this (just missing string in __init__.py). Will push once I've tested.
