### ISSUE TITLE
Hazen v0.5 reports as v0.4

### ISSUE THREAD

**Issue by pcw24601** [GSTT-CSC/hazen#177]
**Describe the bug**
Hazen version number incorrectly reported

**To Reproduce**
`hazen --version` returns `0.4`
`hazen -v` fails with the following error:

```
Traceback (most recent call last):
  File "C:\Users\Paul\hazen-ven-0-5\Scripts\hazen-script.py", line 33, in <module>
    sys.exit(load_entry_point('hazen', 'console_scripts', 'hazen')())
  File "c:\users\paul\documents\bhsct\hazen repo\hazen\hazenlib\__init__.py", line 315, in main
    task = importlib.import_module(f"hazenlib.{arguments['<task>']}")
  File "C:\Users\Paul\.pyenv\pyenv-win\versions\3.9.9\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hazenlib.None'
```

**Expected behavior**
Return `0.5`

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by tomaroberts** [comment]
This is now fixed in release 0.5.1, which is now in the main branch.

See PR #179
