### ISSUE TITLE
Relaxometry task does not work when Hazen installed from Pypi with pip

### ISSUE THREAD

**Issue by pcw24601** [GSTT-CSC/hazen#310]
**Describe the bug**
The relaxometry task fails when run from the command line when hazen has been installed using pip. The template files (used to how to translate / rotate the ROI coordinates to align with the scanned phantom orientation) are not included in the installation.

**To Reproduce**
1. Install hazen using pip in a clean venv
1. Run `hazen relaxometry --plate=4 --calc_t1 path\to\t1\relaxometry\dir`

**Expected behavior**
The relaxometry task should execute without error.

**Screenshots**
```
> hazen relaxometry --plate=4 --calc_t1 .
Traceback (most recent call last):
  File "C:\Users\Paul\.pyenv\pyenv-win\versions\3.10.4\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Paul\.pyenv\pyenv-win\versions\3.10.4\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Paul\Documents\BHSCT\test\venv\Scripts\hazen.exe\__main__.py", line 7, in <module>
  File "C:\Users\Paul\Documents\BHSCT\test\venv\lib\site-packages\hazenlib\__init__.py", line 385, in entry_point
    result = main()
  File "C:\Users\Paul\Documents\BHSCT\test\venv\lib\site-packages\hazenlib\__init__.py", line 369, in main
    result = task.run(**relaxometry_args)
  File "C:\Users\Paul\Documents\BHSCT\test\venv\lib\site-packages\hazenlib\tasks\relaxometry.py", line 1172, in run
    template_dcm = pydicom.read_file(
  File "C:\Users\Paul\Documents\BHSCT\test\venv\lib\site-packages\pydicom\filereader.py", line 1001, in dcmread
    fp = open(fp, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Paul\\Documents\\BHSCT\\test\\venv\\Lib\\site-packages\\hazenlib\\tasks\\data\\relaxometry\\Plate4_T1_signed'
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by pcw24601** [comment]
Suggested fix: add required directory to `MANIFEST.in` and edit `setup.cfg` to include `include_package_data=True` option.
